# Generated by Django 4.2.6 on 2023-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='tg_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
